CREATE TABLE MEMBER(
MNO VARCHAR(5) PRIMARY KEY, MNAME VARCHAR(10) NOT NULL, MID VARCHAR(12) NOT NULL UNIQUE, MPW VARCHAR(20) NOT NULL, MTEL VARCHAR(11) NOT NULL UNIQUE, MMAIL VARCHAR(35) NOT NULL UNIQUE, MANAGER NUMBER(1));

ALTER TABLE MEMBER ADD CONSTRAINT CK_MANAGER CHECK(MANAGER IN (0, 1));

insert into member values('m0001', '∞≠πŒ¡÷', 'KkoKko', 'manager1234','01087338662','minjukang727@gmail.com',1);

select * from member;

commit;